version: "3.4"
  
services:   
  server:
    image: notebook
    container_name: notebook
    restart: unless-stopped
    build:
      context: .
      dockerfile: notebook/Dockerfile  
    environment:
      - ASPNETCORE_ENVIRONMENT=Production       
    ports:   
      - "6500:8080"  
      - "6501:8081"